Revert "Makefile: prohibit VLA"
This reverts commit b41cd77db067c245935903dcac7330d470095662.

I don't own a Poco to properly fix and test this:

drivers/media/platform/msm/camera/cam_sensor_module/cam_sensor/cam_sensor_core.c: In function 'cam_sensor_driver_cmd':
drivers/media/platform/msm/camera/cam_sensor_module/cam_sensor/cam_sensor_core.c:974:10: error: ISO C90 forbids variable length array 'i2c_reg_setting' [-Werror=vla]
  974 |   struct cam_sensor_i2c_reg_array i2c_reg_setting[cmd->size];

Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>